apiVersion: apps/v1
kind: Deployment
metadata:
  name: selise
  labels:
    app: selise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selise
  template:
    metadata:
      labels:
        app: selise
    spec:
      containers:
      - name: selise
        image: marlin1993/selise:16
        ports:
        - containerPort: 80
